### PR TITLE
fix: update from igor to igor2

### LINKED ISSUE #96: Changing Igor to Igor2
I recently found out (when trying to do the same thing) that [Igor2 ](https://github.com/AFM-analysis/igor2
) has supplanted the very old and un-updated Igor, which throws errors with modern version of numpy. 

I will fix this as it's trivial, but wanted to write this issue in part if people Google about Igor2.

### PR DESCRIPTION
**Pull request by nsulmol**
igor no longer works with numpy as of numpy 1.20. If trying to import SciFiReaders with igor, we get the following error:

"AttributeError: module 'numpy' has no attribute 'complex'."

indicating the issue. Because of this deprecation issue, AFM-Analysis have forked the original wking/igor, and updated it into a new repository called igor2.

This CL updates SciFiReaders to use igor2 instead of igor. The igor unit tests have been tested and pass. The changes here correspond exclusively to changing text from 'igor' to 'igor2' for package purposes and user prompts (we do not change any class/variable names).

Note: for 2 files, the diff will show the addition of a \newline at the end of the file. This is unix policy and done by default by my editor.

resolves #96

### CODE REVIEW

**Comment by ramav87** [comment]
Thanks! I believe this also means there will be version incompatibility with python 3.7 since igor2 requires 3.8 or above. I will go ahead and merge this now and then we will remove 3.7 compatibility for SciFiReaders soon.

**Comment by ramav87** [comment]
@gduscher we will need to remove python 3.7 compatibility. Something more to discuss.

**Comment by nsulmol** [comment]
> Thanks! I believe this also means there will be version incompatibility with python 3.7 since igor2 requires 3.8 or above. I will go ahead and merge this now and then we will remove 3.7 compatibility for SciFiReaders soon.

Yes, your test suite caught that (it was not something I had considered, excuse me). The igor2 pyproject.toml explicits that it needs 3.8+. Thank you for pulling it in.

**Comment by rajgiriUW** [comment]
Wonderful!
